# Generated by Django 5.1.1 on 2024-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('brief_story', models.TextField()),
                ('dob', models.DateField()),
                ('date_of_employment', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Retired', 'Retired'), ('Sacked', 'Sacked')], max_length=10)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
